//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhankin.AppConnectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int IdChek { get; set; }
        public int IdTovar { get; set; }
        public string Articul { get; set; }
        public string KolVo { get; set; }
        public int IdZakaz { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
