//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhankin.AppConnectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int IdTovar { get; set; }
        public string Articul { get; set; }
        public string NameTovara { get; set; }
        public string EdIzmerenia { get; set; }
        public double Cena { get; set; }
        public string Postavshik { get; set; }
        public string Proizvoditel { get; set; }
        public string KategoriaTovara { get; set; }
        public int DeistvSkidka { get; set; }
        public string KolvoNaSclade { get; set; }
        public string OpisanieTovara { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
    }
}
