//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhankin.AppConnectBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int IdZakaz { get; set; }
        public string DataZakaza { get; set; }
        public System.DateTime DataPostavki { get; set; }
        public int AdresPunktaVidacha { get; set; }
        public int IdUsers { get; set; }
        public string KodPoluchenia { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
        public virtual PunktVidachi PunktVidachi { get; set; }
        public virtual Users Users { get; set; }
    }
}
